name: Comment on PR
author: Aaron Klaassen <aaron@unsplash.com>
description: Leaves a comment on an open PR matching a push event.
branding:
  icon: 'message-square'  
  color: 'blue'
inputs:
  token:
    description: "A github token. Comes from `{{ secrets.GITHUB_TOKEN }}`"
    required: true
  unique_id:
    description: A unique ID to override comments
    required: true
  file_path:
    description: A file to read
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.file_path }}
    - ${{ inputs.unique_id }}
